# Generated by Django 4.2 on 2024-05-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_answer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
    ]
