# Generated by Django 4.2 on 2024-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_remove_answer_is_active_remove_question_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
